// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"gqlgen-issue/graph/model/types"
)

// An object that has an author.
type Authored interface {
	IsAuthored()
	// The author of this object.
	GetAuthor() *types.Identity
}
