// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/MichaelMure/gqlgen-issue/graph/model/lazyloading"
)

// An object that has an author.
type Authored interface {
	IsAuthored()
	// The author of this object.
	GetAuthor() lazyloading.IdentityWrapper
}
